version: "3.9"

services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    ports:
      - "4317:4317"
      - "55680:55680"
      - "55681:55681"
    restart: unless-stopped

  springboot-app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.otel.buildkit}
    image: springboot-samples/data-jpa-postgresql:${TAG:-latest}
    ports:
      - "8080:8080"
      - "4004:4004"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=springboot-todo-api,service.version=1.0.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    depends_on:
      - collector
