version: "3.9"

services:
  springboot-app:
    environment:
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

  collector:
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
    volumes:
      - type: bind
        source: ./otel-collector/config.honeycomb.yaml
        target: /conf/collector-config.yaml
        read_only: true
