version: "3.9"

services:
  collector:
    environment:
      - DATADOG_API_KEY=${DATADOG_API_KEY}
    volumes:
      - type: bind
        source: ./otel-collector/config.datadog.yaml
        target: /conf/collector-config.yaml
        read_only: true
