version: "3.8"

services:
  springboot-app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.buildkit}
    image: springboot-samples/data-jpa-postgresql:${TAG:-latest}
    ports:
      - 8080:8080
      - 4004:4004
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - APPLICATIONINSIGHTS_ROLE_NAME=${APPLICATIONINSIGHTS_ROLE_NAME:-localhost}
