version: "3.9"

services:

  zookeeper:
    image: ${ZOOKEEPER:-wurstmeister/zookeeper}
    ports:
      - "2181:2181"

  kafka:
    image: ${KAFKA:-wurstmeister/kafka}    
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_CREATE_TOPICS: "usage-cost-processor:1:1,usage-cost-logger:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
