version: "3.9"

volumes:
  message-data:

services:
  message-db:
    image: postgres:${POSTGRES_TAG:-13-alpine}
    ports:
      - "5432:5432"
    volumes:
      - message-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=messages
